### ISSUE TITLE
MainStereoscopicPicture turned into MainPicture

### ISSUE THREAD

**Issue by wunderbarb** [cth103/dcpomatic#22] opened 2023-09-25 21:28 UTC
Not sure whether it is a bug.  

Scenario:
- Create a new content with dcpomatic2
- Add a Dolby 3D DCP
- Request the new content to have the same characteristics as the imported DCP
- Process.

In the CPL, the video in the `AssetList` of the original is `<msp-cpl:MainStereoscopicPicture xmlns:msp-cpl="http://www.smpte-ra.org/schemas/429-10/2008/Main-Stereo-Picture-CPL"> ....</msp-cpl:MainStereoscopicPicture>` whereas in the processed it is claimed as `<MainPicture> ... </MainPicture>`.
I would have expected The identification as `MainStereoscopicPicture` to be maintained, especially since the content remained stereoscopic.

**Comment by cth103** [comment] 2023-09-27 09:19
That's odd, I can't reproduce it.  After you click "Set project settings from this DCP" is the 3D checkbox ticked in the DCP -> video tab?

**Comment by wunderbarb** [comment] 2023-09-27 16:36
I was not precise enough.  I am only using the CLI for the actual conversion.  For that purpose, I have created (via GUI) a template "Dolby3D".  Inside the template file, I found 
`  <Resolution>2K</Resolution>
  <J2KBandwidth>150000000</J2KBandwidth>
  <VideoFrameRate>24</VideoFrameRate>
  <AudioFrameRate>48000</AudioFrameRate>
  <ISDCFDate>20230915</ISDCFDate>
  <AudioChannels>16</AudioChannels>
  <ThreeD>1</ThreeD>` 
  I assumed that `ThreeD = 1` meant 3D version.
  In the CPL of the encrypted DCP, 
  `<msp-cpl:MainStereoscopicPicture xmlns:msp-cpl="http://www.smpte-ra.org/schemas/429-10/2008/Main-Stereo-Picture-CPL">
<Id>urn:uuid:26719f04-6d65-448a-9eae-0f5869c48e43</Id>
<EditRate>24 1</EditRate>
<IntrinsicDuration>23470</IntrinsicDuration>
<EntryPoint>0</EntryPoint>
<Duration>23470</Duration>`
In the CPL of the decrypted DCP
`        <MainPicture>
          <Id>urn:uuid:b239b612-1316-4013-872d-f59f02aebd70</Id>
          <EditRate>24 1</EditRate>
          <IntrinsicDuration>23470</IntrinsicDuration>
          <EntryPoint>0</EntryPoint>
          <Duration>23470</Duration>
          <Hash>vlo7JbLVZ2p2aEgjBj5w8g+vgZg=</Hash>
          <FrameRate>24 1</FrameRate>
          <ScreenAspectRatio>2048 858</ScreenAspectRatio>
        </MainPicture>`
Was the use of the template wrong? I used a template because I did not find a flag in `dcpomatic2_create` that seems to mimic the GUI option to use the parameter of the DCP.  Is there such a flag?

**Comment by cth103** [comment] 2023-09-27 20:32
Ah right, thanks, I see what you mean - the CLI client overwrites some template settings, which does look like a bug.

**Comment by wunderbarb** [comment] 2023-09-27 22:30
> Ah right, thanks, I see what you mean - the CLI client overwrites some template settings, which does look like a bug.

I experimented one step more.  This time, I put both the "Dolby3D" template and the `--threed` flag in the `dcpomatic2_create` command.  At least in the CPL, it uses now the 429-10 space, i.e., we have now the `MainStereoscopicPicture`.  We have not yet verified whether the `mxf` are also in the 429-10 space.
So it seems that the CLI may not take into account the `ThreeD` of the template.

**Comment by cth103** [comment] 2023-09-27 22:38
Right, I think that's exactly the bug - the `--threed` flag (or lack of it) on the command line overrides whatever is in the template.

**Comment by cth103** [comment] 2023-09-30 10:40
This should be fixed by dec7ad14997421accfe0ff9f382f9ffcb4e61ec2 which will be in a release quite soon.

**Closed as completed by cth103** 2023-09-30 10:40 UTC
